import { Geist, Geist_Mono } from "next/font/google";
import axios from "axios";
import "./globals.css";
import getUrl from "@/libs/getUrl";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SmartechLA",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    const response = await axios.get(getUrl()+"/custom/style")
    const color = {
      primary: response.data[0].color,
      secondary: response.data[1].color
    }
  return (
    <html lang="en">
      <head>
        <style
          dangerouslySetInnerHTML={{
            __html: `:root {
              --color-primary: ${color.primary}; 
              --color-secondary: ${color.secondary};
              }`,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
